version: 2
jobs:
  build:
    docker:
      - image: parthibx24/aosp-dockerscripts:kernel-basic
    steps:
      - checkout
      - run:
          name: Setup  
          command: apt-get update; apt-get install make cmake yasm gcc build-essential screen -y; apt-get install ffmpeg handbrake-cli -y; apt-get install libc-ares2 libcrypto++6 libmediainfo0v5 libpcrecpp0v5 libzen0v5 apt-transport-https -y; wget https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megacmd-Debian_9.0_amd64.deb; dpkg -i mega*.deb; rm mega*deb;

      - run:
          name: build
          command: cd Build/linux; bash build.sh release; false;
